import { chromium } from 'playwright-core';
const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const issues=[];
page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')issues.push(`${m.type()}: ${m.text()}`)});
page.on('pageerror',e=>issues.push(`pageerror: ${e.message}`));
await page.addInitScript(()=>localStorage.setItem('localtech-onboarding','done'));
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await page.getByText('Buenas tardes, Iliana').waitFor();
await page.getByRole('button',{name:'Nueva venta'}).click();
await page.getByPlaceholder('Buscar por nombre, categoría o código…').fill('Cuaderno Éxito');
const card=page.locator('article').filter({hasText:'Cuaderno Éxito A4 rayado'}).first();
await card.getByRole('button',{name:/Agregar/}).click();
await page.getByRole('button',{name:'Sumar cantidad'}).click();
await page.getByRole('button',{name:/Cobrar/}).click();
await page.getByRole('button',{name:'Transferencia'}).click();
await page.getByRole('button',{name:'Confirmar venta'}).click();
await page.getByText('Venta registrada correctamente').waitFor();
await page.getByText('$ 16.900').last().waitFor();
await page.getByRole('button',{name:'Volver al inicio'}).click();
await page.getByText('Cuaderno Éxito A4 rayado — quedan 4 unidades').waitFor();
await page.getByRole('button',{name:'Ver producto'}).first().click();
await page.getByText('Movimientos recientes').waitFor();
await page.getByText('Venta #V-1048').waitFor();
await page.getByRole('dialog').getByRole('button',{name:'Registrar ingreso'}).click();
await page.getByLabel('Cantidad recibida *').fill('10');
await page.getByRole('button',{name:'Guardar ingreso'}).click();
const row=page.locator('tr').filter({hasText:'Cuaderno Éxito A4 rayado'});
await row.getByText('14',{exact:true}).waitFor();
await page.getByRole('link',{name:'Reportes'}).click();
await page.getByText('Información clara para tomar mejores decisiones.').waitFor();
await page.getByRole('link',{name:'Productos'}).click();
await page.getByRole('button',{name:'Nuevo producto'}).click();
await page.getByLabel('Nombre *').fill('Producto de prueba');
await page.getByLabel('Código *').fill('TEST-001');
await page.getByLabel('Precio *').fill('2500');
await page.getByLabel('Stock inicial *').fill('8');
await page.getByRole('button',{name:'Guardar producto'}).click();
const productCard=page.locator('article').filter({hasText:'Producto de prueba'});
await productCard.getByText('Producto de prueba').waitFor();
await productCard.getByRole('button',{name:/Editar/}).click();
await page.getByLabel('Precio *').fill('3200');
await page.getByRole('button',{name:'Guardar producto'}).click();
await productCard.getByText('$ 3.200').waitFor();
await productCard.getByRole('button',{name:'Eliminar producto'}).click();
await page.getByText('¿Eliminar este producto?').waitFor();
await page.getByRole('dialog').getByRole('button',{name:'Eliminar producto'}).click();
await page.getByText('Producto de prueba').waitFor({state:'detached'});
await page.getByRole('link',{name:'Configuración'}).click();
await page.getByRole('button',{name:/Restablecer datos de demostración/}).click();
await page.getByRole('button',{name:'Sí, restablecer'}).click();
await page.getByRole('link',{name:'Inventario'}).click();
await page.getByPlaceholder('Buscar por nombre o código...').fill('Cuaderno Éxito');
await page.locator('tr').filter({hasText:'Cuaderno Éxito A4 rayado'}).getByText('6',{exact:true}).waitFor();
console.log(JSON.stringify({ok:true,flow:'venta 6→4, alerta, reposición 4→14, reportes, CRUD producto, reset 14→6',issues},null,2));
await browser.close();
if(issues.length)process.exitCode=2;
